--------------------------------------------------------
--  DDL for Table BANK_STATEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BANK_STATEMENT" 
   (	"ACCNO" NUMBER, 
	"AMOUNT" NUMBER, 
	"R_ACCNO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
